name: .NET CI Build

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore CyberBot_2/CyberBot_2/CyberBot_2.csproj

    - name: Build Project
      run: dotnet build CyberBot_2/CyberBot_2/CyberBot_2.csproj --configuration Release --no-restore
